services:
  # build:
  #   container_name: build
  #   image: gradle:8-jdk17
  #   user: "1000:1000"
  #   command: "gradle --no-build-cache --no-daemon shadowJar"
  #   volumes:
  #     - './:/home/gradle'

  server:
    image: openjdk:17-alpine
    stop_grace_period: 1s
    volumes:
      - './server/build/libs/server.jar:/app/server.jar:ro'
    command: "find /app/ -regex '.*server.*jar' -exec java -jar {} \\;"

  client1:
    image: openjdk:17-alpine
    depends_on:
      - server
    stop_grace_period: 1s
    environment:
      - RMI_USER=user1
      - RMI_PASS=pass1
    volumes:
      - './client/build/libs/client.jar:/app/client.jar:ro'
    command: "find /app/ -regex '.*client.*jar' -exec java -jar {} \\;"

  client2:
    image: openjdk:17-alpine
    stop_grace_period: 1s
    volumes:
      - './client/build/libs/:/app:ro'
    command: "find /app/ -regex '.*client.*jar' -exec java -jar {} \\;"

  client3:
    image: openjdk:17-alpine
    stop_grace_period: 1s
    volumes:
      - './client/build/libs/:/app:ro'
    command: "find /app/ -regex '.*client.*jar' -exec java -jar {} \\;"

  client4:
    image: openjdk:17-alpine
    volumes:
      - './client/build/libs/:/app:ro'
    command: "find /app/ -regex '.*client.*jar' -exec java -jar {} \\;"

  client5:
    image: openjdk:17-alpine
    volumes:
      - './client/build/libs/:/app:ro'
    command: "find /app/ -regex '.*client.*jar' -exec java -jar {} \\;"
