services:
  server:
    container_name: server
    image: my-gradle:latest
    build:
      context: docker
      dockerfile: Dockerfile
    environment:
      - TARGET=server
    healthcheck:
      test: ["CMD-SHELL", "test -f /home/gradle/server/build/build-success.txt && sleep 3"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - './:/app:ro'

  client1:
    container_name: client1
    image: my-gradle:latest
    build:
      context: docker
      dockerfile: Dockerfile
    environment:
      - TARGET=client
    volumes:
      - './:/app:ro'
    depends_on:
      - server

  client2:
    container_name: client2
    image: my-gradle:latest
    build:
      context: docker
      dockerfile: Dockerfile
    environment:
      - TARGET=client
    volumes:
      - './:/app:ro'
    depends_on:
      - server

  client3:
    container_name: client3
    image: my-gradle:latest
    build:
      context: docker
      dockerfile: Dockerfile
    environment:
      - TARGET=client
    volumes:
      - './:/app:ro'
    depends_on:
      - server
